# Generated by Django 6.1 on 2026-08-17 01:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ordemdeservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Abertura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição / Relato do Serviço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo'),
        ),
        migrations.DeleteModel(
            name='OrdemDeServico',
        ),
    ]
