# Generated by Django 6.1 on 2026-08-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ordemservico_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servicos',
            field=models.ManyToManyField(to='core.servico', verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
