# Generated by Django 6.1 on 2026-08-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_veiculo_ano_alter_veiculo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, default='Sem Placa', max_length=10, null=True),
        ),
    ]
