# Generated by Django 6.1 on 2026-09-30 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_veiculo_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio', models.CharField(choices=[('Sócio 1', 'Sócio 1'), ('Sócio 2', 'Sócio 2')], max_length=50, verbose_name='Sócio')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('pro_labore', 'Pró-labore'), ('lucros', 'Distribuição de Lucros'), ('adiantamento', 'Adiantamento')], default='lucros', max_length=20, verbose_name='Tipo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
    ]
