# Generated by Django 6.1 on 2026-10-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_folhapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='socio',
            field=models.CharField(choices=[('Nathannael', 'Nathannael'), ('Carlos Eduardo', 'Carlos Eduardo')], max_length=50, verbose_name='Sócio'),
        ),
    ]
